#!/usr/bin/python

"""Abibao Services.

Usage:
  abibao help
  abibao version
  abibao start [<service>] [--env=<environment>]
  abibao stop [<service>]

Arguments:

Options:

"""
from docopt import docopt

import os

def setenv(args):
    if args['--env'] == None:
        os.environ['SERVICE_ENV'] = 'deve'
    else:
        os.environ['SERVICE_ENV'] = args['--env']

if __name__ == '__main__':
    arguments = docopt(__doc__, version="Abibao Services 2.0.0")
    
    setenv(arguments)

    if arguments['start'] == True:
        os.system('docker-compose --file=' + os.getcwd() + '/services/' + arguments['<service>'] + '/docker-compose.yml up -d')

    if arguments['stop'] == True:
        os.system('docker-compose --file=' + os.getcwd() + '/services/' + arguments['<service>'] + '/docker-compose.yml down')
