#!/usr/bin/python

"""Abibao Services.

Usage:
  abibao help
  abibao version
  abibao start (local|rece|prod)

Arguments:

Options:

"""
from docopt import docopt
import os

if __name__ == '__main__':
    arguments = docopt(__doc__, version="Abibao Services 2.0.0")
    print(arguments)

    os.environ['SERVICE_ENV'] = 'local'

    cmd = 'docker-compose --file=' + os.getcwd() + '/services/communs/docker-compose.yml up -d'
    os.system(cmd)
