version: "3"

services:

  nginx:
    image: library/nginx:1.11.0-alpine
    container_name: infra_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./volumes/nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443

  portainer:
    image: portainer/portainer
    container_name: infra_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  composeui:
    image: francescou/docker-compose-ui:1.8.0
    container_name: infra_composeui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/composeui:/opt/docker-compose-projects:ro

  cadvisor:
    image: google/cadvisor:latest
    container_name: infra_cadvisor
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /:/rootfs:ro

  couchdb:
    image: library/couchdb:1.6
    container_name: infra_couchdb
    environment:
      COUCHDB_USER: infra
      COUCHDB_PASSWORD: infra
    volumes:
      - ./docker/couchdb/default.d:/usr/local/etc/couchdb/default.d
      - ./volumes/couchdb:/usr/local/var/lib/couchdb

  postgres:
    image: library/postgres:9.5-alpine
    container_name: infra_postgres
    environment:
      POSTGRES_USER: infra
      POSTGRES_PASSWORD: infra
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data

  rabbitmq:
    image: library/rabbitmq:3.6-management-alpine
    container_name: infra_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: infra
      RABBITMQ_DEFAULT_PASS: infra

volumes:
  esdata:
    driver: local
