version: "3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/log:/etc/nginx/log
      - ./volumes/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./volumes/nginx/certs:/etc/nginx/certs:rw
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/log:/etc/nginx/log
      - ./volumes/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data
    environment:
      - VIRTUAL_HOST=abibao.portainer.127.0.0.1.xip.io
      - LETSENCRYPT_HOST=abibao.portainer.127.0.0.1.xip.io
      - LETSENCRYPT_EMAIL=team@abibao.com

networks:
  intranet:
    driver: bridge
