version: "3.2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - volumes-data-nginx-certs:/etc/nginx/certs:ro
      - volumes-data-nginx-vhost:/etc/nginx/vhost.d
      - volumes-data-nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - volumes-data-nginx-certs:/etc/nginx/certs:rw
      - volumes-data-nginx-vhost:/etc/nginx/vhost.d
      - volumes-data-nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volumes-data-portainer:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      VIRTUAL_HOST: abibao.portainer.127.0.0.1.xip.io
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: abibao.portainer.127.0.0.1.xip.io
      LETSENCRYPT_EMAIL: team@abibao.com

  jenkins:
    image: library/jenkins:alpine
    volumes:
      - volumes-data-jenkins:/var/jenkins_home
    environment:
      VIRTUAL_HOST: abibao.jenkins.127.0.0.1.xip.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: abibao.jenkins.127.0.0.1.xip.io
      LETSENCRYPT_EMAIL: team@abibao.com

volumes:

  volumes-data-jenkins:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/jenkins

  volumes-data-nginx-certs:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/nginx/certs

  volumes-data-nginx-vhost:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/nginx/vhost

  volumes-data-nginx-html:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/nginx/html

  volumes-data-portainer:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/portainer
