version: "2"

services:

  nginx:
    image: nginx:1.13.0-alpine
    container_name: "nginx-service"
    privileged: true
    volumes:
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/conf.s:/etc/nginx/conf.s
      - ./docker/nginx/log:/var/log/nginx
    networks:
      infra:
        ipv4_address: 172.15.0.2

  portainer:
    image: portainer/portainer
    container_name: "portainer-service"
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer/data:/data
    networks:
      infra:
        ipv4_address: 172.15.0.3

  elasticsearch:
    build: docker/elasticsearch/
    image: abibao/elasticsearch:5.4.0
    container_name: "elasticsearch-service"
    privileged: true
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      infra:
        ipv4_address: 172.15.0.4

  logstash:
    build: docker/logstash/
    image: abibao/logstash:5.4.0
    container_name: "logstash-service"
    volumes:
      - ./docker/logstash/conf.d:/etc/logstash/conf.d
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/logstash/patterns:/opt/logstash/patterns
    command: -f /etc/logstash/conf.d/
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      infra:
        ipv4_address: 172.15.0.5
    depends_on:
      - elasticsearch

  kibana:
    build: docker/kibana/
    image: abibao/kibana:5.4.0
    container_name: "kibana-service"
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config
    networks:
      infra:
        ipv4_address: 172.15.0.6
    depends_on:
      - elasticsearch

networks:
  infra:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1
