#!/bin/bash

# messages
./doktor secret RABBITMQ_DEFAULT_PASS

# databases
./doktor secret COUCHDB_PASSWORD
./doktor secret POSTGRES_PASSWORD
./doktor secret MYSQL_ROOT_PASSWORD
./doktor secret MYSQL_PASSWORD

# wordpress
WORDPRESS_DB_PASSWORD=`cat ./secrets/MYSQL_ROOT_PASSWORD`
arr=(${WORDPRESS_DB_PASSWORD//=/ })
echo WORDPRESS_DB_PASSWORD=${arr[1]} > ./secrets/WORDPRESS_DB_PASSWORD
