version: "2"

services:

    postgres:
      image: library/postgres:9.5-alpine
      container_name: infra_databases_postgres
      environment:
        - POSTGRES_USER=infra
        - POSTGRES_PASSWORD=infra
        - POSTGRES_DB=infra
      networks:
        - proxy
      volumes:
        - ./../../../volumes/postgresql/data:/var/lib/postgresql/data

    couchdb:
      image: library/couchdb:1.6
      container_name: infra_databases_couchdb
      environment:
        - COUCHDB_USER=infra
        - COUCHDB_PASSWORD=infra
      networks:
        - proxy
      volumes:
        - ./couchdb/default.d:/usr/local/etc/couchdb/default.d
        - ./../../../volumes/couchdb:/usr/local/var/lib/couchdb

networks:
  proxy:
    external:
      name: serverinfrastructures_intranet
