version: "3.2"

services:

    postgres:
      image: library/postgres:9.5-alpine
      environment:
        POSTGRES_USER: infra
        POSTGRES_PASSWORD: infra
        POSTGRES_DB: infra
      networks:
        - proxy
      volumes:
        - volumes-data-postgres-data:/var/lib/postgresql/data

    couchdb:
      image: library/couchdb:1.6
      environment:
        COUCHDB_USER: infra
        COUCHDB_PASSWORD: infra
        VIRTUAL_HOST: abibao.couchdb.127.0.0.1.xip.io
        VIRTUAL_PORT: 5984
      networks:
        - proxy
      volumes:
        - volumes-data-couchdb-data:/usr/local/var/lib/couchdb
        - ./couchdb/default.d:/usr/local/etc/couchdb/default.d

volumes:

  volumes-data-postgres-data:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/postgres/data

  volumes-data-couchdb-data:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/couchdb/data

networks:
  proxy:
    external:
      name: serverinfrastructures_default
