version: "3.2"

services:

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    env_file:
      - ${PWD}/environments/${SERVICE_ENV}/rabbitmq.env
      - ${PWD}/secrets/RABBITMQ_DEFAULT_PASS
    networks:
      - proxy
    environment:
      RABBITMQ_DEFAULT_USER: infra

networks:
  proxy:
    external:
      name: communs_default
