version: "3.2"

services:

  elasticsearch:
    build: ./elasticsearch/
    env_file:
      - ${PWD}/environments/${SERVICE_ENV}/elasticsearch.env
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - volumes-data-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - proxy

  logstash:
    build: ./logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - proxy

  kibana:
    build: ./kibana/
    labels:
      - logspout.exclude=true
    env_file:
      - ${PWD}/environments/${SERVICE_ENV}/kibana.env
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    depends_on:
      - elasticsearch
    networks:
      - proxy

  logspout:
    build: ./extensions/logspout/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:5000
      LOGSTASH_TAGS: docker-elk
      EXCLUDE_LABEL: logspout.exclude
    depends_on:
      - logstash
    restart: on-failure
    networks:
      - proxy

volumes:

  volumes-data-elasticsearch-data:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/elasticsearch/data

networks:
  proxy:
    external:
      name: communs_default
