version: "2"

services:

  elasticsearch:
    build: ./elasticsearch/
    container_name: infra_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    networks:
      - proxy

  logstash:
    build: ./logstash/
    container_name: infra_logstash
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
      - ./../../../volumes/nginx/log:/var/log/nginx:ro
    command: -f /etc/logstash/conf.d/
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - proxy

  kibana:
    build: ./kibana/
    container_name: infra_kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - logstash
      - elasticsearch
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=abibao.kibana.127.0.0.1.xip.io
      - LETSENCRYPT_HOST=abibao.kibana.127.0.0.1.xip.io
      - LETSENCRYPT_EMAIL=team@abibao.com

networks:
  proxy:
    external:
      name: serverinfrastructures_intranet
