version: "3.2"

services:

  elasticsearch:
    build: ./elasticsearch/
    volumes:
      - volumes-data-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    networks:
      - proxy

  logstash:
    build: ./logstash/
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    command: -f /etc/logstash/conf.d/
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - proxy

  kibana:
    build: ./kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - logstash
      - elasticsearch
    networks:
      - proxy
    environment:
      VIRTUAL_HOST: abibao.kibana.127.0.0.1.xip.io
      VIRTUAL_PORT: 5601
      LETSENCRYPT_HOST: abibao.kibana.127.0.0.1.xip.io
      LETSENCRYPT_EMAIL: team@abibao.com

volumes:

  volumes-data-elasticsearch-data:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/volumes/data-persist/elasticsearch/data

networks:
  proxy:
    external:
      name: serverinfrastructures_default
